name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version: 12

    - name: Install dependencies
      run: npm ci
    - name: Build app
      run: npm run build

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@v1.5.0
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
