name: Integration Tests

on:
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js for use with actions
              uses: actions/setup-node@v1.1.0
              with:
                  version: 12

            - name: Install dependencies
              run: npm ci
              
            - name: Check translation files
              run: npm run transl
              
            - name: Lint app
              run: npm run lint
              
            - name: Build app
              run: npm run build
              
            # Add tests
            #- name: Build app
            #  run: npm test
